### ISSUE TITLE
build的时候出错

### ISSUE THREAD

**Issue by JZLeung** [ElemeFE/cooking#100]
```
[cooking] - Loaded success: autoprefixer
[cooking] - Failed to read the config.
[cooking] - Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' })

The available options are:
    loader: string | object | loader[]
    fallbackLoader: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (G:\node_modules\global\node_modules\cooking-cli\node_modules\extract-text-webpack-plugin\index.js:172:9)
    at generateLoaders (C:\Users\Leung\.cooking\node_modules\cooking-sass\sass-loader.js:34:29)
    at module.exports (C:\Users\Leung\.cooking\node_modules\cooking-sass\sass-loader.js:41:11)
    at module.exports (C:\Users\Leung\.cooking\node_modules\cooking-sass\index.js:8:14)
    at importExtend (G:\node_modules\global\node_modules\cooking-cli\util\load-extend.js:11:31)
    at G:\node_modules\global\node_modules\cooking-cli\util\load-extend.js:47:5
    at Array.forEach (native)
    at module.exports.Object.keys.reverse.forEach (G:\node_modules\global\node_modules\cooking-cli\util\load-extend.js:32:41)
    at Object.exports.set (G:\node_modules\global\node_modules\cooking-cli\lib\cooking.js:10:3)
    at Object.<anonymous> (G:\html\workspace\Vue-CNode\cooking.conf.js:25:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```
开发环境：Windows 10
```
G:\html\workspace\Vue-CNode>cooking -V
1.1.3

G:\html\workspace\Vue-CNode>node -v
v4.4.4

G:\html\workspace\Vue-CNode>npm -v
3.10.8
```

**Comment by QingWei-Li** [comment]
webpack 只兼容到 beta 22，建议升级下 cooking-cli 或者 cooking 已经锁定版本了

**Comment by JZLeung** [comment]
我的cooking-cli 已经是1.13版本了，应该是最新的了吧？我需要如何操作？

**Comment by QingWei-Li** [comment]
哦 看错了，好像是插件的问题，你把插件都升级到最新。估计是某个 cooking 的样式插件

**Comment by JZLeung** [comment]
如何升级插件。
package.json ：
```
{
  "name": "vue-cnode",
  "version": "0.0.0",
  "description": "CNode",
  "private": true,
  "keywords": [],
  "scripts": {
    "dev": "cooking watch -p",
    "dist": "cooking build -p",
    "deploy": "cooking build --no-color",
    "test": "cooking test karma start --single-run"
  },
  "license": "ISC",
  "dependencies": {
    "vue": "^1.0.0",
    "vue-resource": "^1.0.3",
    "vue-router": "^0.7.13"
  },
  "devDependencies": {
    "vue-loader": "^8.0.0"
  }
}
```

**Comment by QingWei-Li** [comment]
把 ~/.cooking 目录删掉重新装吧 估计你都没升级过

**Comment by JZLeung** [comment]
升级不是 `npm i -g cooking-cli` ？

**Comment by QingWei-Li** [comment]
升级 cooking 的周边插件 http://cookingjs.github.io/zh-cn/list-of-plugins.html

你这个错误是样式相关的插件没升级

**Comment by JZLeung** [comment]
哦哦。好的。
