### ISSUE TITLE
cooking watch 出问题

### ISSUE THREAD

**Issue by lyc152** [ElemeFE/cooking#105]
Listening at http://localhost:8080
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by QingWei-Li** [comment]
请到谷歌上百度下
