### ISSUE TITLE
升级vue2.0.8之后server跑不起来

### ISSUE THREAD

**Issue by terranc** [ElemeFE/cooking#111]
cooking version：1.2.2
cooking-vue2：0.2.3
vue version：2.0.8
webpack-dev-server version：1.14.0

```
***/node_modules/webpack-dev-server/lib/Server.js:25
		throw new OptionsValidationError(validationErrors);
		^
Error
    at new Server (/Volumes/MEDIA/www/sspai.com/node_modules/webpack-dev-server/lib/Server.js:25:9)
    at Object.<anonymous> (/Volumes/MEDIA/www/sspai.com/node_modules/cooking/bin/cooking-watch:58:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**Comment by QingWei-Li** [comment]
OptionsValidationError 是 2.0 才有的，你确定是 1.0 的版本么？
你的 cooking 用的是本地的依赖还是全局的？
只是升级 Vue 么，有改动其他的么？

**Comment by terranc** [comment]
代码没改动。
![image](https://cloud.githubusercontent.com/assets/224353/20469725/02d67848-afdd-11e6-9a96-442c149fb8d1.png)
![image](https://cloud.githubusercontent.com/assets/224353/20469728/08026d90-afdd-11e6-9656-02b4e6ceb67c.png)
![image](https://cloud.githubusercontent.com/assets/224353/20469735/1406f714-afdd-11e6-81f8-888a89c41d31.png)

**Comment by QingWei-Li** [comment]
不确定这样安装后 webpack 和 webpack-dev-server 的版本会是怎么样的 😂
如果 webpack-dev-server 是 1.x 的话就不应该有上面的提示信息，可否知道 `throw new OptionsValidationError(validationErrors);` 抛出的信息是什么呢，还有麻烦看一下安装的 webpack 和 webpack-dev-server 的版本

**Comment by terranc** [comment]
我截图了webpack和webpack-dev-server的版本，是应该用2.x还是用1.x？

**Comment by QingWei-Li** [comment]
都可以，但是要保证 webpack 和 webpack-dev-server 用的是同个大版本号，要么同时 1.x 要么 2.x

**Comment by bibiuc** [comment]
看实际版本npm list -g

**Comment by terranc** [comment]
把webpack和webpack-dev-server都用1.x就没报错了。
