### ISSUE TITLE
不能同时开两个watch即使端口不一样

### ISSUE THREAD

**Issue by bibiuc** [ElemeFE/cooking#120]
### cooking version
1.2.5

### What is Expected?
已经开了一个watch之后,再打开一个 `cooking watch -p`

### What is actually happening?

```
~/.config/yarn/global/node_modules/webpack-dev-server/lib/Server.js:25
		throw new OptionsValidationError(validationErrors);
		^
Error
    at new Server (/home/bbuc/.config/yarn/global/node_modules/webpack-dev-server/lib/Server.js:25:9)
    at Object.<anonymous> (/home/bbuc/.config/yarn/global/node_modules/cooking/bin/cooking-watch:63:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by bibiuc** [comment]
第一个端口8080第二个端口8081
