### ISSUE TITLE
求助:今天升级新版本,build时候遇到webpackOptionsValidationError错误.

### ISSUE THREAD

**Issue by hakunamatatawang** [ElemeFE/cooking#127]
首先贴出cooking.conf.js配置:
```
var path = require('path');
var cooking = require('cooking');

cooking.set({
  entry: {
    app: ['babel-polyfill', './src/main.js']
  },
  dist: './dist',
  template: './index.tpl',

  devServer: {
    port: 8000,
    hostname: 'localhost',
    publicPath: '/'
  },

  // production
  clean: true,
  hash: true,
  sourceMap: true,
  minimize: true,
  chunk: true, // see https://cookingjs.github.io/zh-cn/configuration.html#chunk
  postcss: [
    require('autoprefixer')({
      browsers: ['last 2 versions','ie 6-8','Firefox > 20','> 5%']
    })
  ],
  publicPath: '/',
  assetsPath: 'static',
  urlLoaderLimit: 10000,
  extractCSS: '[name].[contenthash:7].css',
  alias: {
    'src': path.join(__dirname, 'src')
  },
  extends: ['vue2', 'lint', 'autoprefixer']
});

module.exports = cooking.resolve();
```

然后是报的错误:
```
zhanghe@zhanghepc:~/文档/work/VueExample$ cooking build

[cooking] - Loaded success: autoprefixer
[cooking] - Loaded success: lint
[cooking] - Loaded success: vue2


/usr/lib/node_modules/cooking-cli/node_modules/webpack/lib/webpack.js:17
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
Error
    at webpack (/usr/lib/node_modules/cooking-cli/node_modules/webpack/lib/webpack.js:17:9)
    at Object.<anonymous> (/usr/lib/node_modules/cooking-cli/node_modules/cooking/bin/cooking-build:35:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

```

希望指点.非常感谢!

**Comment by QingWei-Li** [comment]
最新发布的 `1.2.10` 已经修复

**Comment by hakunamatatawang** [comment]
@QingWei-Li 这么迅速,给赞.那个文档页面会随着新功能更新文档吗?

**Comment by QingWei-Li** [comment]
哪里有新功能了

**Comment by hakunamatatawang** [comment]
我也就是说说.

**Comment by minerchow** [comment]
![image](https://cloud.githubusercontent.com/assets/3675138/21293026/56d608ce-c553-11e6-8516-f1f3fa11ce7c.png)
![image](https://cloud.githubusercontent.com/assets/3675138/21293031/5cf108e4-c553-11e6-9347-8dc4fe66415c.png)
1.2.10在windows上遇到同样问题

**Comment by QingWei-Li** [comment]
publicPath 必须是字符串，你配置的是啥。。。 @minerchow

**Comment by minerchow** [comment]
哦，发现publicPath配置写错了
