### ISSUE TITLE
windows环境编译sass遇到错误：%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by hcw2175** [ElemeFE/cooking#138]
### cooking version

* 版本：1.3.1
* 系统：win10

### What is Expected?

* 在`main.js`中引入sass文件，编译时出错
* 在`*.vue`文件中标识 `<style lang='sass'></style >`也是一样

### What is actually happening?

```
ERROR in ./~/css-loader!C:/Users/ozhu2/AppData/Roaming/npm/~/cooking-cli/~/postcss-loader!C:/Users/ozhu2/.cooking/~/sass-loader!./src/assets/scss/app.scss
Module build failed: Error: %1 is not a valid Win32 application.
\\?\C:\Users\ozhu2\.cooking\node_modules\node-sass\vendor\win32-x64-48\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\ozhu2\.cooking\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (C:\Users\ozhu2\.cooking\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
 @ ./src/assets/scss/app.scss 4:14-252 13:2-17:4 14:20-258
 @ ./src/main.js
 @ multi app
```

不知道该如何解决呢？

**Comment by QingWei-Li** [comment]
http://www.cnblogs.com/newljc/p/5684223.html

**Comment by hcw2175** [comment]
已经试过了，还是不行，有人说可能是windows上node编译环境问题，需要安装visual studio什么的，这个还没试过。

**Comment by hcw2175** [comment]
用了2种方法解决了，不知道是哪一种起作用了：

1. 安装了visual studio 2013
2. 重新安装`sass-loader`，应该是这个方法解决了

```
npm uninstall sass-loader

npm install sass-loader
```

_提示可能需要依赖`webpack`，那么再安装webpack:`npm install webpack`_
