### ISSUE TITLE
cooking watch／build 时候出现一个警告

### ISSUE THREAD

**Issue by bibiuc** [ElemeFE/cooking#175]
### cooking version
1.5.2

### What is Expected?
cooking watch／build
### What is actually happening?

警告内容
```
(node:13168) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/url-loader/node_modules/file-loader/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/url-loader/node_modules/file-loader/index.js:11:26)
    at Object.module.exports (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/url-loader/index.js:20:21)
    at LOADER_EXECUTION (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/xukaixuan/Projects/taxi/hx-ser/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/xukaixuan/Projects/taxi/hx-ser/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/xukaixuan/Projects/taxi/hx-ser/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:438:3)
```

**Comment by bibiuc** [comment]
最近你们很忙吗？

**Comment by QingWei-Li** [comment]
这个错误可以忽略，等那些依赖升级就可以了，不影响使用
