### ISSUE TITLE
cooking build 报错

### ISSUE THREAD

**Issue by 2016geek** [ElemeFE/cooking#178]
### cooking version

1.5.3
### What is Expected?
希望解决这个问题
### What is actually happening?
执行cooking build 后
`[cooking@1.5.0] - Loaded success: vue2
[cooking@1.5.0] - Loaded success: sass

/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41:9)
    at /Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:567:8)
    at /usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compiler.js:493:16
    at /usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

liuchangdeMacBook-Air:SXP liuchang$ cooking build

[cooking@1.5.0] - Loaded success: vue2
[cooking@1.5.0] - Loaded success: sass

/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41:9)
    at /Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:567:8)
    at /usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compiler.js:493:16
    at /usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

liuchangdeMacBook-Air:SXP liuchang$ cooking build

[cooking@1.5.0] - Loaded success: vue2
[cooking@1.5.0] - Loaded success: sass

/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Chunk.js:41:9)
    at /Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/Users/liuchang/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:567:8)
    at /usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compiler.js:493:16
    at /usr/local/lib/node_modules/cooking-cli/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/usr/local/lib/node_modules/cooking-cli/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by QingWei-Li** [comment]
#180
