### ISSUE TITLE
Error: Cannot find module 'gulp-install'

### ISSUE THREAD

**Issue by Niefee** [ElemeFE/cooking#189]
### cooking version
1.5.2

### What is Expected?

无法初始化项目，已经查过类似问题，但还没有解决。

### What is actually happening?

报错信息：
```
[cooking@1.5.2] - generator project
module.js:487
    throw err;
    ^

Error: Cannot find module 'gulp-install'
    at Function.Module._resolveFilename (module.js:4
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\Ap

    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by luodaoyi** [comment]
体同样的报错信息

**Comment by luodaoyi** [comment]
估计又是kpi产物。。
