### ISSUE TITLE
cooking@1.5.4 TypeError: Cannot read property 'query' of undefined     at getLoaderWithQuery

### ISSUE THREAD

**Issue by tiupcn** [ElemeFE/cooking#196]
### cooking version

1.5.4

node v8.7.0

npm v5.5.1

webpack@2.7.0

### What is Expected?
npm run dev 正常，但是npm run dist报错。

```
[cooking@1.5.4] - Failed to read the config.
[cooking@1.5.4] - TypeError: Cannot read property 'query' of undefined
    at getLoaderWithQuery (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/extract-text-webpack-plugin/index.js:134:13)
    at Array.map (<anonymous>)
    at Function.ExtractTextPlugin.extract (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/extract-text-webpack-plugin/index.js:201:4)
    at extractCSS (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/cooking/util/merge.js:32:25)
    at module.exports (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/cooking/util/merge.js:185:5)
    at Object.exports.set (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/lib/cooking.js:8:17)
    at Object.<anonymous> (/Users/xiaoke/代码/mui-start/cooking.conf.js:4:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/cooking/util/load-config.js:18:14)
    at program.config.forEach.config (/Users/xiaoke/.nvm/versions/node/v8.7.0/lib/node_modules/cooking-cli/node_modules/cooking/bin/cooking-build:27:12)
```
### What is actually happening?

根据报错信息，查找到cooking-cli目录下面，依赖的"extract-text-webpack-plugin"版本为"2.0.0-beta"，更新版本为"extract-text-webpack-plugin": "^2.1.2"后，***问题得以解决***。

**Comment by TNT-Likely** [comment]
同样的问题，修复下吧
