### ISSUE TITLE
cooking 安装后不能运行

### ISSUE THREAD

**Issue by yuedou** [ElemeFE/cooking#33]
>  node版本 V5.5.0
    npm版本 v3.7.0 
    操作系统 ubuntu 14.04
    安装cooking 后 执行报错

```bash
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/cooking/.cooking'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Object.exports.initPluginPackage (/usr/local/lib/node_modules/cooking/util/check.js:19:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/cooking/bin/cooking:14:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)

```
> 执行加上sudo后，显示
```bash
[cooking] - 禁止使用 sudo 执行
```
***这是出了什么问题呢？***

**Comment by QingWei-Li** [comment]
权限问题
#32 #29

**Comment by Jinkeycode** [comment]
运行一下这个命令就好了 sudo chmod -R 777 /usr/local/lib/node_modules/

**Comment by QingWei-Li** [comment]
@Jinkeycode 额别一言不合就 777

改成当前用户的权限就好了

```shell
sudo chown -R 用户名 /usr/local/lib/node_modules/
```
