### ISSUE TITLE
mac下 sudo安装全局的cooking，但是并不能正常使用

### ISSUE THREAD

**Issue by Alex-fun** [ElemeFE/cooking#37]
安装过程提示：
````
graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
````
然后跑个cooking命令就报错：

````
fs.js:842
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/cooking/.cooking'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at Object.exports.initPluginPackage (/usr/local/lib/node_modules/cooking/util/check.js:19:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/cooking/bin/cooking:15:7)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)

````

*will fail on node releases >= v7.0* 感觉这个怪怪的。难道是这个的关系？

**Comment by QingWei-Li** [comment]
权限问题
请看 [readme](https://github.com/ElemeFE/cooking#常见问题)

> 不推荐使用 root 权限安装及执行 cooking，如果强制使用请在每次执行是带上 --allow-root 参数，或者推荐做法是将 node_modules 目录的权限改成当前用户。

> ```shell
> # 找到自己的全局 node_modules 的路径

> sudo chown -R 用户名 /usr/local/lib/node_modules
> ```

#35 #33 #29
