### ISSUE TITLE
eslint-config-standard已经安装了。不知道为啥不好用呢 nodejs-v6.0.0 npm-v3.8.6

### ISSUE THREAD

**Issue by bibiuc** [ElemeFE/cooking#46]
ERROR in ./src/main.js
    Module build failed: Error: Cannot find module 'eslint-config-standard'
    Referenced from: D:\nodejs\api.bluemark.cn\static\.eslintrc.js
        at Object.ModuleResolver.resolve (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\util\module-resolver.js:77:19)
        at resolve (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config\config-file.js:475:33)
        at load (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config\config-file.js:492:24)
        at C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config\config-file.js:388:36
        at Array.reduceRight (native)
        at applyExtends (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config\config-file.js:365:28)
        at Object.load (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config\config-file.js:527:22)
        at loadConfig (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config.js:67:33)
        at getLocalConfig (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config.js:129:23)
        at Config.getConfig (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\config.js:230:22)
        at processText (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\cli-engine.js:149:27)
        at CLIEngine.executeOnText (C:\Users\Adiministrator\.cooking\node_modules\eslint\lib\cli-engine.js:666:26)
        at lint (C:\Users\Adiministrator\.cooking\node_modules\eslint-loader\index.js:25:20)
        at Object.module.exports (C:\Users\Adiministrator\.cooking\node_modules\eslint-loader\index.js:111:3)
     @ multi app
    Child html-webpack-plugin for "index.html":

**Comment by QingWei-Li** [comment]
@bibiuc 

Mac 上没问题，我今晚试试 windows

**Comment by QingWei-Li** [comment]
我的可以成功运行，请确保本地安装了 eslint-config-standard，或者发一下你的 eslintrc 的配置文件看看？

我的配置如下:
```json
```
(eslint 的报错信息)
![image](https://cloud.githubusercontent.com/assets/7565692/15776942/255def68-29be-11e6-9a0c-289bd226b8b6.png)

**Comment by QingWei-Li** [comment]
@bibiuc Hi
请问下问题解决了么？

**Comment by bibiuc** [comment]
问题是没解决。我用window环境都不行。我现在用deepin-linux来弄。完全没问题。我觉得是我的win10的问题，应该是其他插件的系统依赖

**Comment by QingWei-Li** [comment]
你可以试试项目里安装其他的依赖，能不能正常的 require 进来，如果这都不行那就是我代码有问题了。
