### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by boboxiao** [ElemeFE/cooking#49]
你好，装好了，cooking，但是一运行，就报错了

**Comment by QingWei-Li** [comment]
麻烦贴一下错误信息

**Comment by boboxiao** [comment]
/usr/local/lib/node_modules/cooking/util/path.js:2
var homeDir = require('os').homedir()
                            ^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/cooking/util/path.js:2:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cooking/bin/cooking:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by QingWei-Li** [comment]
需要 Node 4 以上
