### ISSUE TITLE
Cannot find module 'cooking-vue'

### ISSUE THREAD

**Issue by bigezhang** [ElemeFE/cooking#51]
node 6.2.1、 npm 3.9.3 环境下安装cooking, 前面执行都正常，到cooking watch 这步时会报错「Error: Failed to read the config. Error: Cannot find module 'cooking-vue'」 请问是什么问题？

**Comment by QingWei-Li** [comment]
重新执行 `cooking watch` 后是否能运行？麻烦贴一下完整的日志

**Comment by bigezhang** [comment]
@QingWei-Li 
[cooking] - Failed to read the config.
[cooking] - Error: Cannot find module 'cooking-vue'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at importExtend (/usr/local/lib/node_modules/cooking/util/load-extend.js:8:3)
    at /usr/local/lib/node_modules/cooking/util/load-extend.js:38:5
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/cooking/util/load-extend.js:29:31)
    at Object.exports.set (/usr/local/lib/node_modules/cooking/lib/cooking.js:26:3)
    at Object.<anonymous> (/Users/bigezhang/freework/cookvue/my-project/cooking.conf.js:4:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

**Comment by QingWei-Li** [comment]
你看一下 `~/.cooking` 是不是 root 权限创建的，如果是的话改一下权限。你是用 sudo 执行过 cooking 么（但是我有过判断如果权限不对会有提示，可能不是这问题）

```shell
sudo chown -R $USER:$(id -gn $USER) ~/.cooking
```

如果还是不对，你把完整的日志发一下，从执行 `cooking watch` 之后的日志

**Comment by bigezhang** [comment]
~/.cooking 不是 root 权限创建的。 我uninstall cooking , 再重装，报错还是一样。

**Comment by QingWei-Li** [comment]
直接把 `~/.cooking` 删掉再运行 `cooking watch`

**Comment by boboxiao** [comment]
@QingWei-Li 
cooking] - generator project
[10:15:15] No local gulp install found in /Users/mac/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the `slush-cooking-vue` generator

**Comment by QingWei-Li** [comment]
@boboxiao 
需要使用 Node4 + 以及 NPM3+ 你这里是没使用 NPM3+ 导致的

**Comment by boboxiao** [comment]
必须NPM3啊？升级到NPM3，会影响别的么？

**Comment by QingWei-Li** [comment]
@boboxiao 
那你可以使用 nvm 或者 n 之类的 Node 版本管理工具。确保 cooking 的项目是在 NPM3 的环境下运行就好了，因为 cooking 使用到了 NPM3 的某些特性。切换到 NPM3 后，把 `~/.cooking` 目录删除掉，重新安装并执行 cooking

**Comment by boboxiao** [comment]
@QingWei-Li 
Thanks ,升级到NPM 3.9后，是乎正常了！

**Comment by boboxiao** [comment]
@QingWei-Li 
但是，执行  cooking watch 报错和上面一样

**Comment by boboxiao** [comment]
@QingWei-Li 
可以了，运行正常！
