### ISSUE TITLE
coding 那个工具安装上之后,无法新建项目 报如下的错误

### ISSUE THREAD

**Issue by xiaxiaodong** [ElemeFE/cooking#67]
C:\Program Files\nodejs\node_modules\cooking\bin\cooking:4 
const path = require('path') ^^^^^
 SyntaxError: Use of const in strict mode. 
at exports.runInThisContext (vm.js:73:16) 
at Module._compile (module.js:443:25) 
at Object.Module._extensions..js (module.js:478:10) a
t Module.load (module.js:355:32) 
at Function.Module._load (module.js:310:12) 
at Function.Module.runMain (module.js:501:10) 
at startup (node.js:129:16) at node.js:814:3

**Comment by QingWei-Li** [comment]
＝ ＝

请在 Node 4+ 以及 NPM 3+ 的环境下运行

**Comment by xiaxiaodong** [comment]
安装最新版node之后,问题已经解决, 
感谢!
