### ISSUE TITLE
cooking watch 报错

### ISSUE THREAD

**Issue by JZLeung** [ElemeFE/cooking#69]
执行 cooking watch 之后就这么报错了。
```
[cooking] - 安装成功

[cooking] - Failed to read the config.
[cooking] - Error: Cannot find module 'cooking/util/check'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/leung/.cooking/node_modules/cooking-vue/css-loader.js:2:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/leung/.cooking/node_modules/cooking-vue/index.js:1:79)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```
删除~/.cooking也不行。
不是sudo安装cooking
Linux： ubuntu16.04
NPM：3.5.2

**Comment by JZLeung** [comment]
```
npm WARN optional Skipping failed optional dependency /cooking/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "cooking" "-g" "--registry=https://registry.npm.taobao.org"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/cooking
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/cooking'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/cooking']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/cooking' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leung/Workspace/projects/npm-debug.log

```
重新安装就这样了。

**Comment by QingWei-Li** [comment]
😂 我正在重构，同时升级并刚刚发布了插件，还没有处理兼容 0.x 的 cooking

需要你到 `.cooking` 目录下手动安装上一版本的 `cooking-vue` 😂😂

**Comment by QingWei-Li** [comment]
弄好了，删除 `~/.cooking` 目录重新安装下插件
