### ISSUE TITLE
cooking build 出错了

### ISSUE THREAD

**Issue by JZLeung** [ElemeFE/cooking#73]
```
[cooking] - 插件加载成功: vue
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: sass

G:\node_modules\global\node_modules\cooking\bin\cooking-build:72
    logger.err(err)
           ^

TypeError: logger.err is not a function
    at G:\node_modules\global\node_modules\cooking\bin\cooking-build:72:12
    at G:\node_modules\global\node_modules\cooking\node_modules\webpack\lib\MultiCompiler.js:104:18
    at G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:52:16
    at G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:361:13
    at G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:52:16
    at done (G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:241:17)
    at G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:44:16
    at G:\node_modules\global\node_modules\cooking\node_modules\async\lib\async.js:358:17
    at Compiler.<anonymous> (G:\node_modules\global\node_modules\cooking\node_modules\webpack\lib\Compiler.js:185:21)
    at Compiler.emitFiles (G:\node_modules\global\node_modules\cooking\node_modules\webpack\lib\Compiler.js:233:18)
    at G:\node_modules\global\node_modules\cooking\node_modules\mkdirp\index.js:47:53
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by QingWei-Li** [comment]
麻烦报一下版本号

**Comment by JZLeung** [comment]
```
G:\html\haodiaoyu\vue-ucenter>cooking --version

0.6.2


G:\html\haodiaoyu\vue-ucenter>npm -v
3.10.6

G:\html\haodiaoyu\vue-ucenter>node -v
v4.4.4
```
在linux下面开发会好一点吗？

**Comment by QingWei-Li** [comment]
因为我并没有在 win 上测试过，只是反馈有 bug 的我都修了。

这个问题是 cooking-build 文件，你把 72 行的 `logger.err` 改成 `logger-error` 看看真正要报什么错，前面是我函数名拼错的

**Comment by JZLeung** [comment]
```
[cooking] - 插件加载成功: vue
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: sass

[cooking] - { [Error: EPERM: operation not permitted, mkdir 'G:\html\haodiaoyu\vue-ucenter\ucenter']
  errno: -4048,
  code: 'EPERM',
  syscall: 'mkdir',
  path: 'G:\\html\\haodiaoyu\\vue-ucenter\\ucenter' }
```

**Comment by QingWei-Li** [comment]
清下缓存试试
```shell
npm cache clean
```

我一会发一版修复 `logger.err` 的问题

**Comment by JZLeung** [comment]
OK，可以了，谢谢。
