### ISSUE TITLE
cooking watch报错

### ISSUE THREAD

**Issue by LiXunGuan** [ElemeFE/cooking#84]
cooking-cli是安装在全局的。然后执行watch就报错了
```
D:\wwwroot\cy-ui>cooking watch


[cooking] - Failed to read the config.
[cooking] - ReferenceError: modules is not defined
    at Object.<anonymous> (D:\wwwroot\cy-ui\cooking.conf.js:10:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (D:\wwwroot\cy-ui\node_modules\cooking\util\load-config.js
:18:14)
    at D:\wwwroot\cy-ui\node_modules\cooking\bin\cooking-watch:24:12
    at Array.forEach (native)
    at Object.<anonymous> (D:\wwwroot\cy-ui\node_modules\cooking\bin\cooking-wat
ch:23:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by QingWei-Li** [comment]
配置使用 cooking 生成的？还是自己写的？ 为啥有个 `modules` ?

**Comment by LiXunGuan** [comment]
自己在根目录下新建``cooking.conf.js``配置如下
``
var cooking = require('cooking');

cooking.set({
  entry: './src/main.js',
  dist: './dist',
  hash: true,
  sourceMap: true
})

modules.export = cooking.resolve();
``
modules是从文档上复制进来的

**Comment by QingWei-Li** [comment]
应该这样写
```javascript
module.exports = cooking.resolve();
```
我去修改下文档

**Comment by QingWei-Li** [comment]
fixed in https://github.com/cookingjs/cookingjs.github.io/commit/e2934c9044a2ffb573510ccdf45d3b4b1e3c18e6

**Comment by LiXunGuan** [comment]
3Q
